// Streaming SHA-256 over the vendored secworks core.
//
//   init pulse            -> begin a new message
//   in_valid/in_data/in_ready  -> feed bytes (multiple bursts over time are fine;
//                                 the wrapper persists partial-block state)
//   fin pulse            -> no more bytes; pad and finish
//   done / digest        -> result; pulse init again for the next message
//
// Padding (0x80, zero-fill, 64-bit big-endian bit length) is generated by feeding
// pad bytes through the same absorb path, so the partial-block / length logic is
// shared with normal data. Blocks are big-endian (first byte at bit 511) via a
// shift-left buffer. First block of a message uses the core's `init` (loads IV),
// later blocks use `next` (continue the chained H state). Verilog-2001.
module sha256_stream(
    input  wire         clk,
    input  wire         reset_n,
    input  wire         init,        // pulse: start a new message
    input  wire         in_valid,    // a byte is offered
    input  wire [7:0]   in_data,
    output wire         in_ready,    // wrapper will accept a byte this cycle
    input  wire         fin,         // pulse: finalize (latched)
    output wire         done,        // level: digest valid
    output wire [255:0] digest
);
    localparam IDLE=0, ABSORB=1, PAD80=2, PADZ=3, PADL=4,
               FIRE=5, WAIT1=6, WAIT2=7, DONE=8;
    localparam RET_ABSORB=0, RET_PADZ=1, RET_FINAL=2;

    reg [3:0]    state;
    reg [511:0]  blk;        // current block, filled MSB-first
    reg [6:0]    cnt;        // bytes in blk, 0..64
    reg [63:0]   bitlen;     // message length in bits
    reg          first;      // next core op is init (vs next)
    reg [1:0]    ret;        // where to resume after a block fire
    reg [3:0]    li;         // length-byte index during PADL
    reg          finl;       // latched fin request

    reg          core_init, core_next;
    wire         core_ready;
    wire [255:0] core_digest;

    sha256_core core(.clk(clk), .reset_n(reset_n), .init(core_init), .next(core_next),
                     .mode(1'b1), .block(blk), .ready(core_ready),
                     .digest(core_digest), .digest_valid());

    assign in_ready = (state == ABSORB) && (cnt != 7'd64);
    assign done     = (state == DONE);
    assign digest   = core_digest;

    function [7:0] lenbyte;
        input [3:0]  i;
        input [63:0] L;
        case (i)
            4'd0: lenbyte = L[63:56]; 4'd1: lenbyte = L[55:48];
            4'd2: lenbyte = L[47:40]; 4'd3: lenbyte = L[39:32];
            4'd4: lenbyte = L[31:24]; 4'd5: lenbyte = L[23:16];
            4'd6: lenbyte = L[15:8];  default: lenbyte = L[7:0];
        endcase
    endfunction

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            state <= IDLE; cnt <= 0; bitlen <= 0; first <= 1;
            core_init <= 0; core_next <= 0; li <= 0; finl <= 0;
        end else begin
            core_init <= 0;
            core_next <= 0;
            if (fin) finl <= 1;       // latch; cleared when finalize starts (below)

            case (state)
                IDLE:
                    if (init) begin cnt <= 0; bitlen <= 0; first <= 1; finl <= 0; state <= ABSORB; end

                ABSORB:                       // drain data first, then finalize
                    if (cnt == 7'd64)       begin ret <= RET_ABSORB; state <= FIRE; end
                    else if (in_valid)        begin blk <= {blk[503:0], in_data};
                                                    cnt <= cnt + 1; bitlen <= bitlen + 8; end
                    else if (finl)            begin finl <= 0; state <= PAD80; end

                PAD80:  begin blk <= {blk[503:0], 8'h80}; cnt <= cnt + 1; state <= PADZ; end

                PADZ:
                    if (cnt == 7'd64)       begin ret <= RET_PADZ; state <= FIRE; end
                    else if (cnt == 7'd56)  begin li <= 0; state <= PADL; end
                    else                      begin blk <= {blk[503:0], 8'h00}; cnt <= cnt + 1; end

                PADL:
                    if (cnt == 7'd64)       begin ret <= RET_FINAL; state <= FIRE; end
                    else begin blk <= {blk[503:0], lenbyte(li, bitlen)}; cnt <= cnt + 1; li <= li + 1; end

                FIRE:  begin core_init <= first; core_next <= ~first; state <= WAIT1; end
                WAIT1: state <= WAIT2;         // core has gone busy (ready low)
                WAIT2:
                    if (core_ready) begin
                        first <= 0; cnt <= 0;
                        state <= (ret == RET_ABSORB) ? ABSORB :
                                 (ret == RET_PADZ)   ? PADZ   : DONE;
                    end

                DONE:
                    if (init) begin cnt <= 0; bitlen <= 0; first <= 1; finl <= 0; state <= ABSORB; end
            endcase
        end
    end
endmodule
