# cocotb testbench for mac_tx_mux.v
TOPLEVEL_LANG    = verilog
TOPLEVEL         = mac_tx_mux
MODULE           = test_mac_tx_mux

REPO_ROOT       := $(realpath $(dir $(lastword $(MAKEFILE_LIST)))/../..)
VERILOG_SOURCES  = $(REPO_ROOT)/gateware/src/core/mac_tx_mux.v

include $(REPO_ROOT)/tb/common.mk
